### ISSUE TITLE
[FEATURE] Handle case where user does not consent to the terms

### ISSUE THREAD

**Issue by ferndot** [joshua-s/coronavirus-diary#31] opened 2020-03-22 22:20 UTC
**Is your feature request related to a problem? Please describe.**
When the user does not consent to the app's usage terms, there is no additional information provided.

**Describe the solution you'd like**
Implement a new screen that notifies the user that they have not consented and will not be able to use the app. Phrase it much better than that :D

**Comment by Hixie** [comment] 2020-03-22 22:36
See also https://github.com/coronavirus-diary/coronavirus-diary/issues/22

**Comment by joshua-s** [comment] 2020-03-22 23:09
Resolving as a duplicate of #22

**Comment by JoseAlba** [comment] 2020-03-23 22:08
I was wondering if another page is necessary it might make more sense to use a [dialog](https://api.flutter.dev/flutter/material/Dialog-class.html) if the message is short.

**Closed as completed** 2020-03-24 20:56 UTC
Labels: type: feature, difficulty: 1
